<?php

namespace Slps970093\LaravelApiResponse\Resources;

use Illuminate\Http\Resources\Json\ResourceResponse;
use Illuminate\Pagination\LengthAwarePaginator;

class PaginatedResourceResponse extends ResourceResponse
{
    protected function wrap($data, $with = [], $additional = [])
    {
        if ($this->resource->resource instanceof LengthAwarePaginator) {
            /** @var LengthAwarePaginator $pageResource */
            $pageResource = $this->resource->resource;
            return [
                $this->wrapper()    => $data,
                'paginate'          => [
                    'current_page'      => $pageResource->currentPage(),
                    'from'              => $pageResource->firstItem(),
                    'last_page'         => $pageResource->lastPage(),
                    'per_page'          => $pageResource->perPage(),
                    'to'                => $pageResource->lastItem(),
                    'total'             => $pageResource->total(),
                ]
            ];
        }

        return parent::wrap($data, $with, $additional); // TODO: Change the autogenerated stub
    }
}